package com.anonymous.ziwy.Utilities

object ZConstants {
    const val FETCH_COUPONS = "FETCH_COUPONS"
    const val EXTRACT_COUPON = "EXTRACT_COUPON"
    const val ADD_COUPON = "ADD_COUPON"
    const val UPDATE_COUPON = "UPDATE_COUPON"

    const val COUPON_IS_EXPIRING_SOON = "COUPON_IS_EXPIRING_SOON"
    const val COUPON_HAS_EXPIRED = "COUPON_HAS_EXPIRED"
    const val COUPON_IS_VALID = "COUPON_IS_VALID"

    const val OTPLESS_REQUEST = "OTPLESS_REQUEST"
    const val GET_USER_DATA = "GET_USER_DATA"
    const val ADD_USER_INFO = "ADD_USER_INFO"
    const val APP_UPDATE_INFO = "APP_UPDATE_INFO"
    const val EXPIRY_NOTIFICATION = "EXPIRY_NOTIFICATION"

    const val FETCH_CARDS = "FETCH_CARDS"
    const val FETCH_USER_CARDS = "FETCH_USER_CARDS"
    const val FETCH_CARDS_LIST = "FETCH_CARDS_LIST"
    const val UPDATE_USER_CARDS = "UPDATE_USER_CARDS"
}